import os

BEGIN = "# Begin user definition\n"
HINT = "# These lines between `Begin` and `End` is auto generated by merge.py\n"
END = "# End user definition\n"

USER_DICT = "./user.dict"
SIMP_DICT = "./cangjie6.extsimp.dict.yaml"

def merge():
    lines = None
    with open(SIMP_DICT, 'r') as simpp:
        lines = simpp.readlines()

    if lines is None:
        return False

    start = 0
    while lines[start] != '...\n':
        start += 1

    start += 1
    if start >= len(lines):
        return False

    head = lines[:start]
    tail = lines[lines.index(END) + 1:] if END in lines else lines[start:]

    head.append(BEGIN)
    head.append(HINT)

    with open(USER_DICT) as userp:
        head.extend(userp.readlines())

    head.append(END)
    head.extend(tail)

    with open(SIMP_DICT, 'w') as simpp:
        simpp.writelines(head)

if __name__ == '__main__':
    merge()
